name: system_date_time_format
description: A plugin for getting date and time format patterns from device system settings.
version: 1.3.0
repository: https://github.com/Nikoro/system_date_time_format
issue_tracker: https://github.com/Nikoro/system_date_time_format/issues

environment:
  sdk: ^3.2.0
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4

flutter:
  assets:
    - web/system_date_time_format.min.js

  plugin:
    platforms:
      android:
        package: com.dominikkrajcer.system_date_time_format
        pluginClass: SystemDateTimeFormatPlugin
      ios:
        pluginClass: SystemDateTimeFormatPlugin
      linux:
        pluginClass: SystemDateTimeFormatPlugin
      macos:
        pluginClass: SystemDateTimeFormatPlugin
      windows:
        pluginClass: SystemDateTimeFormatPluginCApi
      web:
        pluginClass: SystemDateTimeFormatWeb
        fileName: system_date_time_format_web.dart
